import catalog1 from "../../assets/images/catalog/catalog-1.jpg";
import catalog2 from "../../assets/images/catalog/catalog-2.jpg";
import catalog3 from "../../assets/images/catalog/catalog-3.jpg";
import catalog4 from "../../assets/images/catalog/catalog-4.jpg";
import catalog5 from "../../assets/images/catalog/catalog-5.jpg";
import catalog6 from "../../assets/images/catalog/catalog-6.jpg";
import catalog7 from "../../assets/images/catalog/catalog-7.jpg";
import catalog8 from "../../assets/images/catalog/catalog-8.jpg";
import catalog9 from "../../assets/images/catalog/catalog-9.jpg";
import catalog10 from "../../assets/images/catalog/catalog-10.jpg";
import catalog11 from "../../assets/images/catalog/catalog-11.jpg";
import catalog12 from "../../assets/images/catalog/catalog-12.jpg";

export const catalog = [
  {
    img: catalog1,
    id: 1,
    title: "Лучший день",
    price: 3500,
    mark: "popular",
  },
  {
    img: catalog2,
    id: 2,
    title: "Лучший день - 2",
    price: 4000,
    mark: "sale",
  },
  {
    img: catalog3,
    id: 3,
    title: "Лучший день - 3",
    price: 7500,
  },
  {
    img: catalog4,
    id: 4,
    title: "Лучший день - 4",
    price: 6200,
  },
  {
    img: catalog5,
    id: 5,
    title: "Лучший день - 5",
    price: 2500,
    mark: "popular",
  },
  {
    img: catalog6,
    id: 6,
    title: "Лучший день - 6",
    price: 3800,
  },
  {
    img: catalog7,
    id: 7,
    title: "Лучший день - 7",
    price: 9000,
    mark: "popular",
  },
  {
    img: catalog8,
    id: 8,
    title: "Лучший день - 8",
    price: 1500,
    mark: "sale",
  },
  {
    img: catalog9,
    id: 9,
    title: "Лучший день - 9",
    price: 3000,
    mark: "new",
  },
  {
    img: catalog10,
    id: 10,
    title: "Лучший день - 10",
    price: 3500,
  },
  {
    img: catalog11,
    id: 11,
    title: "Лучший день - 11",
    price: 7000,
    mark: "sale",
  },
  {
    img: catalog12,
    id: 12,
    title: "Лучший день - 12",
    price: 5600,
    mark: "popular",
  },
  {
    img: catalog1,
    id: 1,
    title: "Лучший день",
    price: 3500,
    mark: "new",
  },
  {
    img: catalog2,
    id: 2,
    title: "Лучший день - 2",
    price: 4000,
  },
  {
    img: catalog3,
    id: 3,
    title: "Лучший день - 3",
    price: 7500,
  },
  {
    img: catalog4,
    id: 4,
    title: "Лучший день - 4",
    price: 6200,
  },
  {
    img: catalog5,
    id: 5,
    title: "Лучший день - 5",
    price: 2500,
  },
  {
    img: catalog6,
    id: 6,
    title: "Лучший день - 6",
    price: 3800,
    mark: "popular",
  },
  {
    img: catalog7,
    id: 7,
    title: "Лучший день - 7",
    price: 9000,
  },
  {
    img: catalog8,
    id: 8,
    title: "Лучший день - 8",
    price: 1500,
  },
  {
    img: catalog9,
    id: 9,
    title: "Лучший день - 9",
    price: 3000,
  },
  {
    img: catalog10,
    id: 10,
    title: "Лучший день - 10",
    price: 3500,
  },
  {
    img: catalog11,
    id: 11,
    title: "Лучший день - 11",
    price: 7000,
    mark: "popular",
  },
  {
    img: catalog12,
    id: 12,
    title: "Лучший день - 12",
    price: 5600,
  },
  {
    img: catalog1,
    id: 1,
    title: "Лучший день",
    price: 3500,
    mark: "new",
  },
  {
    img: catalog2,
    id: 2,
    title: "Лучший день - 2",
    price: 4000,
  },
  {
    img: catalog3,
    id: 3,
    title: "Лучший день - 3",
    price: 7500,
    mark: "popular",
  },
  {
    img: catalog4,
    id: 4,
    title: "Лучший день - 4",
    price: 6200,
  },
  {
    img: catalog5,
    id: 5,
    title: "Лучший день - 5",
    price: 2500,
  },
  {
    img: catalog6,
    id: 6,
    title: "Лучший день - 6",
    price: 3800,
  },
  {
    img: catalog7,
    id: 7,
    title: "Лучший день - 7",
    price: 9000,
  },
  {
    img: catalog8,
    id: 8,
    title: "Лучший день - 8",
    price: 1500,
    mark: "popular",
  },
  {
    img: catalog9,
    id: 9,
    title: "Лучший день - 9",
    price: 3000,
    mark: "new",
  },
  {
    img: catalog10,
    id: 10,
    title: "Лучший день - 10",
    price: 3500,
  },
  {
    img: catalog11,
    id: 11,
    title: "Лучший день - 11",
    price: 7000,
  },
  {
    img: catalog12,
    id: 12,
    title: "Лучший день - 12",
    price: 5600,
  },
  {
    img: catalog1,
    id: 1,
    title: "Лучший день",
    price: 3500,
  },
  {
    img: catalog2,
    id: 2,
    title: "Лучший день - 2",
    price: 4000,
    mark: "popular",
  },
  {
    img: catalog3,
    id: 3,
    title: "Лучший день - 3",
    price: 7500,
  },
  {
    img: catalog4,
    id: 4,
    title: "Лучший день - 4",
    price: 6200,
    mark: "sale",
  },
  {
    img: catalog5,
    id: 5,
    title: "Лучший день - 5",
    price: 2500,
  },
  {
    img: catalog6,
    id: 6,
    title: "Лучший день - 6",
    price: 3800,
  },
  {
    img: catalog7,
    id: 7,
    title: "Лучший день - 7",
    price: 9000,
  },
  {
    img: catalog8,
    id: 8,
    title: "Лучший день - 8",
    mark: "sale",
    price: 1500,
  },
  {
    img: catalog9,
    id: 9,
    title: "Лучший день - 9",
    price: 3000,
    mark: "sale",
  },
  {
    img: catalog10,
    id: 10,
    title: "Лучший день - 10",
    price: 3500,
  },
  {
    img: catalog11,
    id: 11,
    title: "Лучший день - 11",
    price: 7000,
  },
  {
    img: catalog12,
    id: 12,
    title: "Лучший день - 12",
    price: 5600,
  },
  {
    img: catalog1,
    id: 1,
    title: "Лучший день",
    price: 3500,
  },
  {
    img: catalog2,
    id: 2,
    title: "Лучший день - 2",
    price: 4000,
    mark: "sale",
  },
  {
    img: catalog3,
    id: 3,
    title: "Лучший день - 3",
    price: 7500,
    mark: "new",
  },
  {
    img: catalog4,
    id: 4,
    title: "Лучший день - 4",
    price: 6200,
  },
  {
    img: catalog5,
    id: 5,
    title: "Лучший день - 5",
    price: 2500,
  },
  {
    img: catalog6,
    id: 6,
    title: "Лучший день - 6",
    price: 3800,
    mark: "sale",
  },
  {
    img: catalog7,
    id: 7,
    title: "Лучший день - 7",
    price: 9000,
  },
  {
    img: catalog8,
    id: 8,
    title: "Лучший день - 8",
    price: 1500,
  },
  {
    img: catalog9,
    id: 9,
    title: "Лучший день - 9",
    price: 3000,
  },
  {
    img: catalog10,
    id: 10,
    title: "Лучший день - 10",
    price: 3500,
    mark: "sale",
  },
  {
    img: catalog11,
    id: 11,
    title: "Лучший день - 11",
    price: 7000,
    mark: "new",
  },
  {
    img: catalog12,
    id: 12,
    title: "Лучший день - 12",
    price: 5600,
  },
  {
    img: catalog1,
    id: 1,
    title: "Лучший день",
    price: 3500,
  },
  {
    img: catalog2,
    id: 2,
    title: "Лучший день - 2",
    price: 4000,
  },
  {
    img: catalog3,
    id: 3,
    title: "Лучший день - 3",
    price: 7500,
    mark: "sale",
  },
  {
    img: catalog4,
    id: 4,
    title: "Лучший день - 4",
    price: 6200,
    mark: "new",
  },
  {
    img: catalog5,
    id: 5,
    title: "Лучший день - 5",
    price: 2500,
  },
  {
    img: catalog6,
    id: 6,
    title: "Лучший день - 6",
    price: 3800,
  },
  {
    img: catalog7,
    id: 7,
    title: "Лучший день - 7",
    price: 9000,
  },
  {
    img: catalog8,
    id: 8,
    title: "Лучший день - 8",
    price: 1500,
  },
  {
    img: catalog9,
    id: 9,
    title: "Лучший день - 9",
    price: 3000,
  },
  {
    img: catalog10,
    id: 10,
    title: "Лучший день - 10",
    price: 3500,
    mark: "sale",
  },
  {
    img: catalog11,
    id: 11,
    title: "Лучший день - 11",
    price: 7000,
  },
  {
    img: catalog12,
    id: 12,
    title: "Лучший день - 12",
    price: 5600,
  },
  {
    img: catalog1,
    id: 1,
    title: "Лучший день",
    price: 3500,
    mark: "new",
  },
  {
    img: catalog2,
    id: 2,
    title: "Лучший день - 2",
    price: 4000,
    mark: "popular",
  },
  {
    img: catalog3,
    id: 3,
    title: "Лучший день - 3",
    price: 7500,
  },
  {
    img: catalog4,
    id: 4,
    title: "Лучший день - 4",
    price: 6200,
  },
  {
    img: catalog5,
    id: 5,
    title: "Лучший день - 5",
    price: 2500,
  },
  {
    img: catalog6,
    id: 6,
    title: "Лучший день - 6",
    price: 3800,
  },
  {
    img: catalog7,
    id: 7,
    title: "Лучший день - 7",
    price: 9000,
  },
  {
    img: catalog8,
    id: 8,
    title: "Лучший день - 8",
    price: 1500,
  },
  {
    img: catalog9,
    id: 9,
    title: "Лучший день - 9",
    price: 3000,
  },
  {
    img: catalog10,
    id: 10,
    title: "Лучший день - 10",
    price: 3500,
  },
  {
    img: catalog11,
    id: 11,
    title: "Лучший день - 11",
    price: 7000,
  },
  {
    img: catalog12,
    id: 12,
    title: "Лучший день - 12",
    price: 5600,
  },
  {
    img: catalog1,
    id: 1,
    title: "Лучший день",
    price: 3500,
    mark: "sale",
  },
  {
    img: catalog2,
    id: 2,
    title: "Лучший день - 2",
    price: 4000,
  },
  {
    img: catalog3,
    id: 3,
    title: "Лучший день - 3",
    price: 7500,
  },
  {
    img: catalog4,
    id: 4,
    title: "Лучший день - 4",
    price: 6200,
  },
  {
    img: catalog5,
    id: 5,
    title: "Лучший день - 5",
    price: 2500,
  },
  {
    img: catalog6,
    id: 6,
    title: "Лучший день - 6",
    price: 3800,
  },
  {
    img: catalog7,
    id: 7,
    title: "Лучший день - 7",
    price: 9000,
  },
  {
    img: catalog8,
    id: 8,
    title: "Лучший день - 8",
    price: 1500,
  },
  {
    img: catalog9,
    id: 9,
    title: "Лучший день - 9",
    price: 3000,
  },
  {
    img: catalog10,
    id: 10,
    title: "Лучший день - 10",
    price: 3500,
  },
  {
    img: catalog11,
    id: 11,
    title: "Лучший день - 11",
    price: 7000,
  },
  {
    img: catalog12,
    id: 12,
    title: "Лучший день - 12",
    price: 5600,
  },
  {
    img: catalog1,
    id: 1,
    title: "Лучший день",
    price: 3500,
  },
  {
    img: catalog2,
    id: 2,
    title: "Лучший день - 2",
    price: 4000,
  },
  {
    img: catalog3,
    id: 3,
    title: "Лучший день - 3",
    price: 7500,
  },
  {
    img: catalog4,
    id: 4,
    title: "Лучший день - 4",
    price: 6200,
  },
  {
    img: catalog5,
    id: 5,
    title: "Лучший день - 5",
    price: 2500,
  },
  {
    img: catalog6,
    id: 6,
    title: "Лучший день - 6",
    price: 3800,
  },
  {
    img: catalog7,
    id: 7,
    title: "Лучший день - 7",
    price: 9000,
  },
  {
    img: catalog8,
    id: 8,
    title: "Лучший день - 8",
    price: 1500,
  },
  {
    img: catalog9,
    id: 9,
    title: "Лучший день - 9",
    price: 3000,
  },
  {
    img: catalog10,
    id: 10,
    title: "Лучший день - 10",
    price: 3500,
  },
  {
    img: catalog11,
    id: 11,
    title: "Лучший день - 11",
    price: 7000,
  },
  {
    img: catalog12,
    id: 12,
    title: "Лучший день - 12",
    price: 5600,
  },
  {
    img: catalog1,
    id: 1,
    title: "Лучший день",
    price: 3500,
  },
  {
    img: catalog2,
    id: 2,
    title: "Лучший день - 2",
    price: 4000,
    mark: "sale",
  },
  {
    img: catalog3,
    id: 3,
    title: "Лучший день - 3",
    price: 7500,
  },
  {
    img: catalog4,
    id: 4,
    title: "Лучший день - 4",
    price: 6200,
  },
  {
    img: catalog5,
    id: 5,
    title: "Лучший день - 5",
    price: 2500,
  },
  {
    img: catalog6,
    id: 6,
    title: "Лучший день - 6",
    price: 3800,
  },
  {
    img: catalog7,
    id: 7,
    title: "Лучший день - 7",
    price: 9000,
  },
  {
    img: catalog8,
    id: 8,
    title: "Лучший день - 8",
    price: 1500,
  },
  {
    img: catalog9,
    id: 9,
    title: "Лучший день - 9",
    price: 3000,
  },
  {
    img: catalog10,
    id: 10,
    title: "Лучший день - 10",
    price: 3500,
  },
  {
    img: catalog11,
    id: 11,
    title: "Лучший день - 11",
    price: 7000,
  },
  {
    img: catalog12,
    id: 12,
    title: "Лучший день - 12",
    price: 5600,
  },
  {
    img: catalog1,
    id: 1,
    title: "Лучший день",
    price: 3500,
  },
  {
    img: catalog2,
    id: 2,
    title: "Лучший день - 2",
    price: 4000,
  },
  {
    img: catalog3,
    id: 3,
    title: "Лучший день - 3",
    price: 7500,
  },
  {
    img: catalog4,
    id: 4,
    title: "Лучший день - 4",
    price: 6200,
  },
  {
    img: catalog5,
    id: 5,
    title: "Лучший день - 5",
    price: 2500,
  },
  {
    img: catalog6,
    id: 6,
    title: "Лучший день - 6",
    price: 3800,
  },
  {
    img: catalog7,
    id: 7,
    title: "Лучший день - 7",
    price: 9000,
  },
  {
    img: catalog8,
    id: 8,
    title: "Лучший день - 8",
    price: 1500,
  },
  {
    img: catalog9,
    id: 9,
    title: "Лучший день - 9",
    price: 3000,
  },
  {
    img: catalog10,
    id: 10,
    title: "Лучший день - 10",
    price: 3500,
  },
  {
    img: catalog11,
    id: 11,
    title: "Лучший день - 11",
    price: 7000,
  },
  {
    img: catalog12,
    id: 12,
    title: "Лучший день - 12",
    price: 5600,
  },
  {
    img: catalog1,
    id: 1,
    title: "Лучший день",
    price: 3500,
  },
  {
    img: catalog2,
    id: 2,
    title: "Лучший день - 2",
    price: 4000,
  },
  {
    img: catalog3,
    id: 3,
    title: "Лучший день - 3",
    price: 7500,
  },
  {
    img: catalog4,
    id: 4,
    title: "Лучший день - 4",
    price: 6200,
    mark: "new",
  },
  {
    img: catalog5,
    id: 5,
    title: "Лучший день - 5",
    price: 2500,
  },
  {
    img: catalog6,
    id: 6,
    title: "Лучший день - 6",
    price: 3800,
    mark: "new",
  },
  {
    img: catalog7,
    id: 7,
    title: "Лучший день - 7",
    price: 9000,
  },
  {
    img: catalog8,
    id: 8,
    title: "Лучший день - 8",
    price: 1500,
  },
  {
    img: catalog9,
    id: 9,
    title: "Лучший день - 9",
    price: 3000,
  },
  {
    img: catalog10,
    id: 10,
    title: "Лучший день - 10",
    price: 3500,
  },
  {
    img: catalog11,
    id: 11,
    title: "Лучший день - 11",
    price: 7000,
    mark: "sale",
  },
  {
    img: catalog12,
    id: 12,
    title: "Лучший день - 12",
    price: 5600,
    mark: "sale",
  },
];

export const catalogLists = [
  {
    title: "готовые букеты из сухоцветов",
    list: ["букеты", "для интерьера", "Композиции"],
  },
  {
    title: "Цветы",
    list: [
      "Сборные букеты",
      "Монобукеты",
      "Композиции из цветов",
      "розы",
      "свадебные",
    ],
  },
  {
    title: "дополнительно",
    list: ["шары", "игрушки", "открытки", "упаковка"],
  },
];

export const howOrder = [
  {
    title: "1 шаг",
    desc: "Выберите какие цветы или подарки вы хотите купить",
  },
  {
    title: "2 шаг",
    desc: "Оформите заказ, и мы отправим вам подтверждение на электронную почту, а так же менеджер свяжется с вами по телефону или в WhatsApp",
  },
  {
    title: "3 шаг",
    desc: "Наши флористы бережно подойдут к созданию букета цветов в самом начале дня или накануне",
  },
  {
    title: "4 шаг",
    desc: "Один из наших курьеров или партнёров доставит ваш заказ по указанному адресу. Мы отправим вам сообщение в Whats App как только заказ будет доставлен",
  },
  {
    title: "5 шаг",
    desc: "Наслаждайтесь цветами , если вы заказали их для дома или любовью, которой поделились, если вы заказали для друга",
  },
];

export const additional = [
  {
    title: "Удобрения для срезанных цветов",
    desc: "При указании об этом в пожеланиях к букету, мы приложим пакетик удобрения для вас",
  },
  {
    title: "подпишем открытку",
    desc: "В пожеланиях к букету укажите текст, какой хотите разместить и выберите на сайте саму открытку",
  },
  {
    title: "Фото букета перед отправкой",
    desc: "В примечании к заказу укажите об этом и мы отправим фото готового букета перед доставкой. В праздничные дни в связи с большой загруженностью такой возможности нет",
  },
  {
    title: "Букет-сюрприз",
    desc: "Если хотите, чтобы получатель не знал, что ему вручат а также от кого, то укажите об этом в примечании к заказу",
  },
];

export const howPay = [
  {
    title: "Способы оплаты:",
    list: [
      "БАНКОВСКОЙ КАРТОЙ ПРИ ОФОРМЛЕНИИ ЗАКАЗА ЧЕРЕЗ САЙТ",
      "НАЛИЧНЫМИ ИЛИ БАНКОВСКОЙ КАРТОЙ ПРИ САМОВЫВОЗЕ",
      "НАЛИЧНЫМИ ПРИ ДОСТАВКЕ КУРЬЕРОМ",
      "КРИПТОВАЛЮТОЙ ОНЛАЙН",
    ],
  },
  {
    title: "стоимость доставки:",
    list: [
      "Бесплатно – при заказе на сумму от 90 рублей",
      "10 рублей – при заказе на сумму менее 90 рублей",
      "Возможность, сроки и стоимость доставки за пределы МКАД, доставки в ночное время, праздники оговариваются с менеджером",
      "Так же вы можете забрать ваш заказ самостоятельно по адресу: г. Минск, ул. Тимирязева д. 67, комн. 112 ежедневно с 10.00 до 21.00",
    ],
  },
  {
    title: "Условия доставки:",
    list: [
      "Доставка осуществляется по городу Минску в пределах МКАД в любой день с 09.00 до 22.00. Доставка в ночное время осуществляется по договоренности с оператором",
    ],
  },
];

export const contacts = [
  {
    title: "время работы",
    desc: "с 10:00 до 21:00 без выходных",
  },
  {
    title: "Адрес",
    desc: "г. Минск, ул. Тимирязева 67, комн. 112",
  },
  {
    title: "Телефон",
    desc: "+375 (29) 113-69-69",
  },
  {
    title: "E-mail",
    desc: "zakaz@loverflower.by",
  },
];

export const corporation = [
  {
    title: "Количество заявок в месяц",
    list: ["1-2", "3-10", "Более 10"],
  },
  {
    title: "Приятные бонусы",
    list: [
      "Стоимость одной доставки по Минску – 10 рублей, за пределы МКАД – от 20 рублей",
      "Доставка бесплатно. Букет-подарок руководителю в его День рождения",
      "Доставка бесплатно. Букет-подарок руководителю в его День рождения. Праздничная ель перед Новым годом",
    ],
  },
];

export const steps = [
  {
    title: "этапы работы:",
    list: [
      "Заполнение заявки",
      "Подписание договора",
      "Вручение цветов",
      "Отчет о доставленных заказах",
      "оплата",
    ],
  },
];
